### ISSUE TITLE
little bit more info on build steps

### ISSUE THREAD

**Issue by shortthefomo** [Xahau/Xahau-Docs#12]
https://github.com/Xahau/Xahau-Docs/blob/9d745e93737461de3605b6507c75319d8b4c66d4/infrastructure/building-xahau/mac-os-13.5.2.md?plain=1#L168

Add line to show new dev how to launch this once built

**Comment by WietseWind** [comment]
Thanks :D

**Comment by shortthefomo** [comment]
PR here https://github.com/Xahau/Xahau-Docs/pull/13
