### ISSUE TITLE
Update mainnet version

### ISSUE THREAD

**Issue by tequdev** [Xahau/Xahau-Docs#8]
The version of the document(download link) differs from the latest version of the network.

https://docs.xahau.network/infrastructure/peering/connect-to-xahau-mainnet#peering-info

It would be nice to have a link to the listing page.
https://build.xahau.tech/

**Comment by WietseWind** [comment]
Good point, changed it to a generic reference + link to the build server output :)

**Comment by tequdev** [comment]
In addition, it would be useful to have a link to the doc page (https://docs.xahau.network/) in the Github Repo.

<img width="536" alt="スクリーンショット 2024-01-26 1 08 55" src="https://github.com/Xahau/Xahau-Docs/assets/69445828/4b1462db-8692-4963-90c6-01757193b1ef">

**Comment by WietseWind** [comment]
Good one as well, done!
